---
title: "Athletes by sport type and nations"
author: "Duc-Quang Nguyen"
date: "2 Aug 2016"
output: html_document
---


## Data

### Grouping of sports
* Grouping of olympic sports: https://en.wikipedia.org/wiki/Olympic_sports
* https://en.wikipedia.org/wiki/Combat_sport#Olympic_Combat_Sports
* Team sports: https://en.wikipedia.org/wiki/Team_sport#Olympic_team_sports


```{r setup, include=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)

### Interactive 
library(ggiraph)
library(svglite)
library(htmltools)
library(swiRcharts)

rio.file <- "input/athletes_rio2016.csv"
sports.file <- "input/summer Olympic sport grouping - Sheet1.csv"

countries <- data.frame(names = c(
  "Switzerland", "Brazil", "United States", "China", "Russia", 
   "India", "Japan", "Turkey", "Germany", "Italy", "Portugal", "France", 
  "Spain", "United Kingdom")
)
countries$ioc <- countrycode(countries$names, "country.name", "ioc")

### Misc stuff
#require(classInt)
#require(viridis)
```

```{r load data}
athletes <- read_csv(rio.file)
sports <- read_csv(sports.file)

idx <- match(athletes$sport, sports$sport)
stopifnot(!any(is.na(idx)))
athletes$group <- unlist(sports[idx, 'group'], use.names = F)

dat <- athletes %>% group_by(group, country, iso3) %>% summarise(value = length(athletes)) %>% ungroup()
dat %<>% group_by(country, iso3) %>% mutate(total = sum(value)) %>% ungroup()
dat$prop <- round((dat$value / dat$total) * 100)


data <- dat %>% filter(iso3 %in% countries$ioc)
d.all <- data %>% group_by(group) %>% 
  summarise(prop.all = (sum(value, na.rm = T) / sum(dat$value)) * 100) %>% 
  ungroup() %>% arrange(desc(prop.all))
d.all$group <- factor(d.all$group, levels = d.all$group)

# order factors
data$group <- factor(data$group, levels = d.all$group)
data$country <- gsub("Russian Federation", "Russia", data$country)
data$country <- factor(data$country, levels = as.character(countries$names))
data$iso2c <- countrycode(data$iso3, "ioc", "iso2c")


```

```{r visualize trial}
### ggplot2 theme
myTheme <- function(base_family = "OpenSans-CondensedLight", title_family = "OpenSans-CondensedBold") {
  swi_theme(base_family = base_family, title_family = title_family, y_gridlines = F) +
    theme(
      #strip.switch.pad.wrap = unit(0.01, "mm"),
      strip.text.x = element_text(family = title_family, hjust = 0, vjust = 1, size = 14),
      axis.text.x = element_text(angle = 45, hjust = 1,  margin = margin(t = -10), size = 10),
      axis.line.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.position  = "none",
      plot.margin = unit(c(0.1, 0.2, 0, 0.1), "mm")
    )   
}

ggplot(data = data, aes(x = country, y = prop, group = country, fill = country)) + 
  geom_bar(stat = "identity") + facet_wrap(~ group, ncol = 4, scales = "free_y") + 
  myTheme() + 
  scale_fill_manual(values = swi_rpal, drop=FALSE) +
  scale_x_discrete(name = "", expand = c(0,0)) +
  geom_hline(data = d.all, aes(yintercept = prop.all), linetype = 7, size = 0.2, alpha = 0.6) +
  geom_text(aes(label = iso2c), vjust=1.5, color = "#f7f5ed", family =  "OpenSans-CondensedBold", size = 2.2)

```

## Generate each sport group as a standaline graphic

(instead of faceting)

```{r prod graphics}
### print interactive chart
interactive_chart <- function(gpath, fontname = 'Open Sans Condensed') {
  ggiraph(
    code = {print(gpath)},
    hover_css = "stroke-opacity:0.5;stroke-width:1px;stroke:black;",
    tooltip_opacity = 0.7,
    pointsize = 15,
    width = "100%",
    height_svg = 5,
    width_svg = 5,
    fontname_sans = fontname,
    fontname_serif = fontname
  ) 
}


gr <- 'Team Sports'

charts <- lapply(levels(data$group), function(gr) {
  chart <- ggplot(data = data %>% filter(group == gr), aes(x = country, y = prop, group = country, fill = country)) + 
    geom_bar_interactive(stat = "identity")  +
    myTheme() + 
    scale_fill_manual(values = swi_rpal, drop = F) +
    scale_x_discrete(name = "", expand = c(0,0.05), drop=FALSE) +
    ylab("")
  gg <- chart +
    geom_hline(data = d.all %>% filter(group == gr), aes(yintercept = prop.all), linetype = 3, size = 0.5, alpha = 0.6) +
    geom_text(aes(label = iso2c), vjust=1.5, color = "#f7f5ed", family =  "OpenSans-CondensedBold", size = 1.5) 
  gg
})

# interactive!
charts <- lapply(levels(data$group), function(gr) {
  chart <- ggplot(data = data %>% filter(group == gr), aes(x = country, tooltip = country, data_id_ = country, y = prop, group = country, fill = country)) + 
    geom_bar_interactive(stat = "identity")  +
    myTheme() + 
    scale_fill_manual(values = swi_rpal, drop = F) +
    scale_x_discrete(name = "", expand = c(0,0.05), drop=FALSE) +
    ylab("")
  gg <- chart +
    geom_hline(data = d.all %>% filter(group == gr), aes(yintercept = prop.all), linetype = 3, size = 0.5, alpha = 0.6) +
    geom_text(aes(label = iso2c), vjust = 1.6, color = "#f7f5ed", family =  "OpenSans-CondensedBold", size = 1.8) 
  gg
})



## test
 save_html(
  tags$html(
    tags$head(includeHTML("styles.html")),
    tags$body(
    h2(HTML("Main title")),
    div(class = "descr",  HTML("general description")),
    div(class = "container",
        div(
          class = "graphic", 
          h3(HTML(levels(data$group)[1])),
          div(class = "subtitle",  HTML("list of sports asdfasdfdas asdf asdfdsaf asfasdf asdfas asd asdfasdf asdf asdfasf")),
          suppressMessages(htmlSVG(print(charts[[1]]), width = 5, height = 5, bg = "#F7F7F7"))),
        div(
          class = "graphic", 
          h3(HTML(levels(data$group)[2])),
          div(class = "subtitle",  HTML("list of sports asdfasdfdas asdf")),
          suppressMessages(htmlSVG(print(charts[[2]]), width = 5, height = 5, bg = "#F7F7F7")))
    ),
    div(id = "cite", HTML("source tasdfasdf")),
    HTML(iframeresizer)
    )), file = "test.html"
  )
 
 
 
 ## interactive test
 save_html(
  tags$html(
    tags$head(includeHTML("styles.html")),
    tags$body(
    h2(HTML("Main title")),
    div(class = "descr",  HTML("general description")),
    div(class = "container",
        div(
          class = "graphic", 
          h3(HTML(levels(data$group)[1])),
          div(class = "subtitle",  HTML("list of sports asdfasdfdas asdf asdfdsaf asfasdf asdfas asd asdfasdf asdf asdfasf")),
          interactive_chart(charts[[1]])
          ),
        div(
          class = "graphic", 
          h3(HTML(levels(data$group)[2])),
          div(class = "subtitle",  HTML("list of sports asdfasdfdas asdf")),
          interactive_chart(charts[[2]])
        )
    ),
    div(id = "cite", HTML("source tasdfasdf")),
    HTML(iframeresizer)
    )), file = "interactive_test.html", libdir = "js"
  )
 
 
 


```