---
title: "Athletes by sport type and nations"
author: "Duc-Quang Nguyen"
date: "2 Aug 2016"
output: html_document
---


## Data

* Grouping of olympic sports: https://en.wikipedia.org/wiki/Olympic_sports

```{r setup, include=FALSE}
library(readr)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)

### Interactive 
library(htmltools)
library(shiny)
library(swiRcharts)

rio.file <- "input/athletes_rio2016.csv"

### Misc stuff
#require(classInt)
#require(viridis)
```

```{r load data}
athletes <- read_csv(rio.file)

sports <- data.frame(sport = unique(athletes$sport))
sports$group <- c(
  'Archery', 'Gymnastics', 'Athletics', 'Badminton',
  'Basketball', 'Volleyball', 'Boxing', 'Canoe',
  'Canoe', 'Cycling', 'Cycling', 'Cycling', 
  'Cycling', 'Aquatics', 'Equestrian', 'Fencing',
  'Football', 'Handball', 'Hockey', 'Judo',
  'Aquatics', 'Pentathlon', 'Gymnastics', 'Rowing',
  'Rugby', 'Sailing', 'Shooting', 'Aquatics',
  'Aquatics', 'Table-tennis', 'Taekwondo', 'Tennis',
  'Gymnastics', 'Triathlon', 'Volleyball', 'Aquatics',
  'Weightlifting', 'Wrestling'
)

write.csv(sports, "data/sports.csv", row.names = F)
```